name: Wrapper tests

on:
  push:
    branches: [ main, fix-workflow ]
  pull_request:
    branches: [ main, fix-workflow ]

jobs:
  test_wrapper:
    name: Test Python wrapper
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install BaseGraph
        run: |
          git clone https://github.com/antoineallard/base_graph.git
          cd base_graph
          cmake -B build
          cmake --build build
          cmake --install build
          pip install .
          cd ..

      - name: Install BaseGraph and dependencies
        run: |
          pip install --upgrade pip
          pip install -r tests/requirements.txt
          pip install .

      - name: Test
        shell: bash
        run: pytest
